{
 "title": "Scout Suite Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Infrastructure Health",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  (\r\n    (sum(aws_resources_count) * sum(aws_rules_count))\r\n    - sum(aws_flagged_items)\r\n  )\r\n  /\r\n  (sum(aws_resources_count) * sum(aws_rules_count))\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Security Overview",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  (\r\n    (aws_resources_count{service=\"ec2\"} * aws_rules_count{service=\"ec2\"})\r\n    - aws_flagged_items{service=\"ec2\"}\r\n  )\r\n  /\r\n  (aws_resources_count{service=\"ec2\"} * aws_rules_count{service=\"ec2\"})\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EC2 Checks",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "aws_checked_items{service=\"ec2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_flagged_items{service=\"ec2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_resources_count{service=\"ec2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_rules_count{service=\"ec2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evaluated Security Rules",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "aws_rule_checked_items", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU utilization per instance [max %]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total network traffic outbound (+) and inbound (-) [bytes/sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "label": "Inbound",
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "*" },
     "label": "Outbound",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}